"""Render an :class:`InfraSpec` into deployable artifacts.

The whole point of the optimizer is that its output feeds the IaC tools with no
manual retyping, so these renderers emit the **exact** shapes the Terraform root
module (``terraform/variables.tf``) and the Pulumi config loader
(``pulumi/components/config.py``) expect:

* ``to_terraform_tfvars`` — nested HCL objects (``network``/``kubernetes``/
  ``database``/``load_balancer``) plus the top-level ``single_nat_gateway`` var.
* ``to_pulumi_config``    — structured Pulumi stack config under the
  ``ai-infra-as-code:`` namespace (``single_nat_gateway`` nested in ``network``),
  plus ``aws:region`` for the AWS provider.
* ``to_yaml`` / ``to_json`` — the canonical spec for review / storage / history.
"""

from __future__ import annotations

import json

from .spec import InfraSpec

try:  # YAML is optional; used only for the canonical-spec renderer.
    import yaml  # type: ignore

    _HAS_YAML = True
except Exception:  # pragma: no cover
    _HAS_YAML = False

PULUMI_NAMESPACE = "ai-infra-as-code"


# --------------------------------------------------------------------------- #
# Terraform (*.auto.tfvars)
# --------------------------------------------------------------------------- #
def _hcl_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    return f'"{v}"'


def _hcl_block(name: str, pairs, quote_keys: bool = False) -> str:
    lines = [f"{name} = {{"]
    width = max((len(k) for k, _ in pairs), default=0)
    for key, value in pairs:
        k = f'"{key}"' if quote_keys else key
        pad = " " * (width - len(key))
        lines.append(f"  {k}{pad} = {_hcl_scalar(value)}")
    lines.append("}")
    return "\n".join(lines)


def to_terraform_tfvars(infra: InfraSpec) -> str:
    """Render nested tfvars matching ``terraform/variables.tf`` exactly."""
    n, k, d, lb = infra.network, infra.kubernetes, infra.database, infra.load_balancer
    parts = [
        "# Generated by aiopt — do not edit by hand.",
        "",
        f'project     = "{infra.project}"',
        f'region      = "{infra.region}"',
        f'environment = "{infra.environment}"',
        "",
        _hcl_block("network", [
            ("vpc_cidr", n.vpc_cidr),
            ("az_count", n.az_count),
        ]),
        "",
        _hcl_block("kubernetes", [
            ("version", k.version),
            ("node_instance_type", k.node_instance_type),
            ("node_min", k.node_min),
            ("node_max", k.node_max),
            ("node_desired", k.node_desired),
        ]),
        "",
        _hcl_block("database", [
            ("engine", d.engine),
            ("engine_version", d.engine_version),
            ("instance_class", d.instance_class),
            ("allocated_storage_gb", d.allocated_storage_gb),
            ("multi_az", d.multi_az),
        ]),
        "",
        _hcl_block("load_balancer", [
            ("type", lb.type),
            ("internet_facing", lb.internet_facing),
        ]),
        "",
        # single_nat_gateway is a top-level variable in the Terraform root.
        f"single_nat_gateway = {_hcl_scalar(n.single_nat_gateway)}",
        "",
        _hcl_block("tags", list(infra.tags.items()), quote_keys=True),
        "",
    ]
    return "\n".join(parts)


# --------------------------------------------------------------------------- #
# Pulumi (Pulumi.<stack>.yaml)
# --------------------------------------------------------------------------- #
def _yaml_scalar(v) -> str:
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    # Quote version-like strings so YAML keeps them strings, not numbers.
    s = str(v)
    if s and (s.replace(".", "", 1).isdigit()):
        return f'"{s}"'
    return s


def to_pulumi_config(infra: InfraSpec, stack: str = "dev") -> str:
    """Render structured Pulumi stack config matching
    ``pulumi/components/config.py`` (``cfg.require_object`` sections)."""
    ns = PULUMI_NAMESPACE
    n, k, d, lb = infra.network, infra.kubernetes, infra.database, infra.load_balancer
    lines = [
        f"# Generated by aiopt for the '{stack}' stack — do not edit by hand.",
        "config:",
        f"  aws:region: {infra.region}",
        f"  {ns}:project: {infra.project}",
        f"  {ns}:region: {infra.region}",
        f"  {ns}:environment: {infra.environment}",
        f"  {ns}:network:",
        f"    vpc_cidr: {n.vpc_cidr}",
        f"    az_count: {n.az_count}",
        f"    single_nat_gateway: {_yaml_scalar(n.single_nat_gateway)}",
        f"  {ns}:kubernetes:",
        f"    version: {_yaml_scalar(k.version)}",
        f"    node_instance_type: {k.node_instance_type}",
        f"    node_min: {k.node_min}",
        f"    node_max: {k.node_max}",
        f"    node_desired: {k.node_desired}",
        f"  {ns}:database:",
        f"    engine: {d.engine}",
        f"    engine_version: {_yaml_scalar(d.engine_version)}",
        f"    instance_class: {d.instance_class}",
        f"    allocated_storage_gb: {d.allocated_storage_gb}",
        f"    multi_az: {_yaml_scalar(d.multi_az)}",
        f"  {ns}:load_balancer:",
        f"    type: {lb.type}",
        f"    internet_facing: {_yaml_scalar(lb.internet_facing)}",
    ]
    if infra.tags:
        lines.append(f"  {ns}:tags:")
        for key, value in infra.tags.items():
            lines.append(f"    {key}: {value}")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Canonical spec
# --------------------------------------------------------------------------- #
def to_yaml(infra: InfraSpec) -> str:
    if _HAS_YAML:
        return yaml.safe_dump(infra.to_dict(), default_flow_style=False, sort_keys=False)
    return to_json(infra)


def to_json(infra: InfraSpec) -> str:
    return json.dumps(infra.to_dict(), indent=2) + "\n"
